### PR TITLE
Updates to run on modern Meteor

### PR DESCRIPTION
**Pull request by Ulexus**
Old version no longer runs on modern Meteor tools; this fixes and modernizes.

### CODE REVIEW

**Comment by theelee13** [comment]
Do I need to approve this somehow?

**Comment by Ulexus** [comment]
If you'd like.  I cannot do it, since I do not have write access to the repository

**Comment by Ulexus** [comment]
For that matter, Meteor 1.4 was just released, so I should probably update the PR using that

**Comment by Ulexus** [comment]
Closing with preference to #3

**Pull request closed without merging**
